<B>LIBRARIES ARE IMPORTING</B>

In [ ]:
import os
from skimage import data
import numpy as np
from pandas import DataFrame
from sklearn.model_selection import train_test_split

In [ ]:
from scipy import misc
import os
from PIL import Image
import scipy.misc
import imageio
from skimage.transform import rescale, resize
from matplotlib import pyplot as plt

<b>Setting path</b>

In [ ]:
from google.colab import drive

drive.mount('/content/gdrive/', force_remount=True)

Mounted at /content/gdrive/


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


Iterating through the folder

In [ ]:
from skimage import io
X=[]
y=[]
base_path='/content/drive/MyDrive/CNNFOLDER/CNN-20221201T051607Z-001/CNN'
source_path=base_path
for child in os.listdir(source_path):
    print(child)
    sub_path = os.path.join(source_path, child)
    bsub_path = os.path.join(base_path, child)
    if os.path.isdir(sub_path):
        count=0
        for data_file in os.listdir(sub_path):
            Qry = Image.open(os.path.join(sub_path, data_file))
            Qry =Qry.convert("L")
            Qry = np.array(Qry.resize((224,224)))
            Qry = Qry.reshape([224,224,1])
            flist=np.array(Qry)
            X.append(flist)
            y.append(child)

PNEUMONIA
Covid
NORMAL


In [ ]:
X

[array([[[17],
         [18],
         [17],
         ...,
         [91],
         [87],
         [88]],
 
        [[15],
         [17],
         [19],
         ...,
         [90],
         [91],
         [87]],
 
        [[16],
         [15],
         [19],
         ...,
         [91],
         [85],
         [79]],
 
        ...,
 
        [[ 0],
         [ 0],
         [ 0],
         ...,
         [ 0],
         [ 0],
         [ 0]],
 
        [[ 0],
         [ 0],
         [ 0],
         ...,
         [ 0],
         [ 0],
         [ 0]],
 
        [[ 0],
         [ 0],
         [ 0],
         ...,
         [ 0],
         [ 0],
         [ 0]]], dtype=uint8),
 array([[[85],
         [65],
         [74],
         ...,
         [61],
         [62],
         [63]],
 
        [[83],
         [70],
         [75],
         ...,
         [60],
         [61],
         [64]],
 
        [[99],
         [81],
         [64],
         ...,
         [62],
         [61],
         [60]],
 
        .

In [ ]:
y

['PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEU

making an array

In [ ]:
images_arr = np.asarray(X)
images_arr = images_arr.astype('float32')
images_arr = images_arr / np.max(images_arr)

resizing the image and storing it in X

In [ ]:
X=[]
for i in range(images_arr.shape[0]):
    img= resize(images_arr[i] ,(224,224,1),anti_aliasing=True)
    X.append(img)

In [ ]:
#label binarizing the array values
X=np.asarray(X)
X = X.astype('float32')
from sklearn.preprocessing import LabelBinarizer
labelBinarizer = LabelBinarizer()
y=labelBinarizer.fit_transform(y)
print(y)

[[0 0 1]
 [0 0 1]
 [0 0 1]
 ...
 [0 1 0]
 [0 1 0]
 [0 1 0]]


In [ ]:
y.shape

(528, 3)

In [ ]:
X.shape

(528, 224, 224, 1)

<b> spliting training and testing set</b>

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

In [ ]:
print(len(X_train))
len(y_train)

422


422

In [ ]:
y_train.shape[1]

3

In [ ]:
y_train

array([[0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       ...,
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1]])

<b> Importing models</b>

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Activation,Flatten,Dropout
import random
import tensorflow as tf
from tensorflow.keras.optimizers import SGD

In [ ]:
import keras
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.layers import BatchNormalization
from tensorflow.keras.layers import Input,Conv2D,MaxPooling2D,Conv2DTranspose

<b>Define the model</b>

In [ ]:
def CNN_model():
  random.seed(42)
  np.random.seed(42)
  tf.random.set_seed(42)
  cnnModel= Sequential()
  cnnModel.add(Conv2D(64, (5,5) , padding = 'same', activation="relu", input_shape=(224,224,1)))
  cnnModel.add(Conv2D(64, (5,5) , padding = 'same', activation="relu"))
  cnnModel.add(Conv2D(64, (5,5) , padding = 'same', activation="relu"))
  cnnModel.add(MaxPooling2D((2,2)))
  cnnModel.add(Conv2D(128, (5,5) , padding = 'same', activation="relu"))
  cnnModel.add(Conv2D(128, (5,5) , padding = 'same', activation="relu"))
  cnnModel.add(MaxPooling2D((2,2)))
  cnnModel.add(Conv2D(128, (5,5) , padding = 'same', activation="relu"))
  cnnModel.add(Conv2D(128, (5,5) , padding = 'same', activation="relu"))
  cnnModel.add(Conv2D(128, (5,5) , padding = 'same', activation="relu"))
  cnnModel.add(MaxPooling2D((2,2)))
  cnnModel.add(Flatten())
  cnnModel.add(Dense(100,activation="relu"))
  cnnModel.add(Dense(200,activation="relu"))
  cnnModel.add(Dense(3,activation="softmax"))
  cnnModel.summary()
  cnnModel.compile(optimizer='sgd',loss="categorical_crossentropy",metrics=["accuracy"])
  return cnnModel


In [ ]:
#model structure
model = CNN_model()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_8 (Conv2D)           (None, 224, 224, 64)      1664      
                                                                 
 conv2d_9 (Conv2D)           (None, 224, 224, 64)      102464    
                                                                 
 conv2d_10 (Conv2D)          (None, 224, 224, 64)      102464    
                                                                 
 max_pooling2d_3 (MaxPoolin  (None, 112, 112, 64)      0         
 g2D)                                                            
                                                                 
 conv2d_11 (Conv2D)          (None, 112, 112, 128)     204928    
                                                                 
 conv2d_12 (Conv2D)          (None, 112, 112, 128)     409728    
                                                      

<b>Complie the model</b>

In [ ]:
#assigning learning rate for the optimizer
sgd = SGD(learning_rate=0.01)

In [ ]:
model.save("CNNMODEL.h5")

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [ ]:
from keras.models import load_model

In [ ]:
model = load_model('/content/CNNMODEL.h5')

<b>Fit the model</b>

In [ ]:
cp_callback = tf.keras.callbacks.ModelCheckpoint(filepath="/content/checkpoint.ckpt",
                                                 save_weights_only=True,
                                                 verbose=1)

In [ ]:
model.fit(X_train,y_train,epochs=100,batch_size=64,verbose=1,validation_split=0.1,callbacks=[cp_callback])

Epoch 1/100
6/6 [==============================] - ETA: 0s - loss: 1.0901 - accuracy: 0.3509
Epoch 1: saving model to /content/checkpoint.ckpt
6/6 [==============================] - 5s 926ms/step - loss: 1.0901 - accuracy: 0.3509 - val_loss: 1.0872 - val_accuracy: 0.3953
Epoch 2/100
6/6 [==============================] - ETA: 0s - loss: 1.0884 - accuracy: 0.3509
Epoch 2: saving model to /content/checkpoint.ckpt
6/6 [==============================] - 5s 895ms/step - loss: 1.0884 - accuracy: 0.3509 - val_loss: 1.0846 - val_accuracy: 0.3953
Epoch 3/100
6/6 [==============================] - ETA: 0s - loss: 1.0857 - accuracy: 0.3509
Epoch 3: saving model to /content/checkpoint.ckpt
6/6 [==============================] - 5s 927ms/step - loss: 1.0857 - accuracy: 0.3509 - val_loss: 1.0818 - val_accuracy: 0.3953
Epoch 4/100
6/6 [==============================] - ETA: 0s - loss: 1.0821 - accuracy: 0.3615
Epoch 4: saving model to /content/checkpoint.ckpt
6/6 [==============================] - 5s

<b>Evaluate Model</b>

In [ ]:
testLoss, testAccuracy = model.evaluate(X_test,y_test)
print("Test Accuracy =", testAccuracy)

4/4 [==============================] - 0s 102ms/step - loss: 0.3465 - accuracy: 0.8962
Test Accuracy = 0.8962264060974121


In [ ]:
# Loads the weights
model.load_weights("/content/checkpoint.ckpt")

# Re-evaluate the model
loss, acc = model.evaluate(X_test,y_test, verbose=2)
print("Restored model, accuracy: {:5.2f}%".format(100 * acc))


4/4 - 0s - loss: 0.3465 - accuracy: 0.8962 - 466ms/epoch - 116ms/step
Restored model, accuracy: 89.62%


predicting one of the image belongs to which category

In [ ]:
Qry = Image.open("/content/drive/MyDrive/CNNFOLDER/CNN-20221201T051607Z-001/CNN/PNEUMONIA/person100_bacteria_481.jpeg")
img=Qry.resize((224,224))
Qry =Qry.convert("L")
Qry = np.array(Qry.resize((224,224)))
Qry = Qry.reshape([1,224,224])
flist=np.array(Qry)
flist=np.asarray(flist)
flist=flist.astype('float32')
flist= flist.reshape([1,224,224])
flist= flist/np.max(flist)
y_predict=model.predict(flist)
pred = labelBinarizer.inverse_transform(y_predict)

1/1 [==============================] - 0s 29ms/step


In [ ]:
pred  #its belong to pneumonia class

array([[0, 0, 1]])

In [ ]:
y_predict

array([[4.1233892e-07, 3.0413916e-05, 9.9996912e-01]], dtype=float32)