# text data

In [ ]:
#importing tensorflow
import tensorflow as tf

In [ ]:
#initializing the data values
numbers = [23, 45,12, -23, 57, -54, -57, 34, 56, 67]

In [ ]:
#converting to df
df = tf.data.Dataset.from_tensor_slices(numbers)
df

<_TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>

In [ ]:
#getting each numbers
for sales in df:
  print(sales.numpy())

23
45
12
-23
57
-54
-57
34
56
67


In [ ]:
#first 3 values are taken
for sales in df.take(3):
  print(sales.numpy())

23
45
12


In [ ]:
#filtering numbers >0
df = df.filter(lambda x: x>0)
for sales in df.as_numpy_iterator():
    print(sales)

23
45
12
57
34
56
67


In [ ]:
#coverting $ to RS
df = df.map(lambda x: x*83)
for sales in df.as_numpy_iterator():
  print(sales)

1909
3735
996
4731
2822
4648
5561


In [ ]:
#shuffling
df = df.shuffle(3)
for sales in df.as_numpy_iterator():
  print(sales)

996
3735
2822
4731
1909
4648
5561


In [ ]:
#batch processing
for sales in df.batch(3):
  print(sales.numpy())

[ 996 1909 3735]
[4648 5561 2822]
[4731]


In [ ]:
#using pipeline the processes are performed
df = tf.data.Dataset.from_tensor_slices(numbers)
df = df.filter(lambda x: x>0).map(lambda y: y*83).shuffle(2).batch(3)

for sales in df.as_numpy_iterator():
  print(sales)

[1909 3735 4731]
[2822 4648  996]
[5561]


# Image data

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
#converting as a dataset
img = tf.data.Dataset.list_files("/content/drive/MyDrive/PROJECT DETAILS/Samples/*/*", shuffle = False)

for file in img.take(3):
  print(file.numpy())

b'/content/drive/MyDrive/PROJECT DETAILS/Samples/Encrypted/encrypted_fruit_F.jpeg'
b'/content/drive/MyDrive/PROJECT DETAILS/Samples/Encrypted/fruit_encrypted.jpeg'
b'/content/drive/MyDrive/PROJECT DETAILS/Samples/image/HorizonZero.png'


In [ ]:
#shuffle images
img = img.shuffle(10)
for file in img.take(3):
  print(file.numpy())

b'/content/drive/MyDrive/PROJECT DETAILS/Samples/image/sunflower.jpg'
b'/content/drive/MyDrive/PROJECT DETAILS/Samples/image/fruit_image_F.jpeg'
b'/content/drive/MyDrive/PROJECT DETAILS/Samples/Encrypted/encrypted_fruit_F.jpeg'


In [ ]:
img_count = len(img)
img_count

7

In [ ]:
train_size = int(img_count*0.8)

In [ ]:
#splitting into train and test
train_img = img.take(train_size)
test_img = img.skip(train_size)

In [ ]:
def get_label(file_path):
  import os
  return tf.strings.split(file_path,os.path.sep)[-2]

In [ ]:
#trainset to numpy
for t in train_img.take(4):
  print(t.numpy())

b'/content/drive/MyDrive/PROJECT DETAILS/Samples/image/fruit_image_F.jpeg'
b'/content/drive/MyDrive/PROJECT DETAILS/Samples/image/fruit.jpeg'
b'/content/drive/MyDrive/PROJECT DETAILS/Samples/image/sunflower.jpg'
b'/content/drive/MyDrive/PROJECT DETAILS/Samples/image/HorizonZero.png'


In [ ]:
#printing the label
for label in train_img.map(get_label):
  print(label)

tf.Tensor(b'image', shape=(), dtype=string)
tf.Tensor(b'image', shape=(), dtype=string)
tf.Tensor(b'Encrypted', shape=(), dtype=string)
tf.Tensor(b'image', shape=(), dtype=string)
tf.Tensor(b'Encrypted', shape=(), dtype=string)


In [ ]:
#processing the image
def process_img(file_path):
  label = get_label(file_path)

  img = tf.io.read_file(file_path)
  img = tf.image.decode_jpeg(img)
  img = tf.image.resize(img, [128,128])

  return img, label

In [ ]:
#result using pipeline
for imge, labels in train_img.map(process_img).take(3):
  print(imge)
  print(labels)

tf.Tensor(
[[[ 89.5   89.5   89.5 ]
  [135.25 135.25 135.25]
  [149.75 149.75 149.75]
  ...
  [ 70.75  70.75  70.75]
  [154.25 154.25 154.25]
  [156.5  156.5  156.5 ]]

 [[125.   125.   125.  ]
  [ 93.75  93.75  93.75]
  [137.5  137.5  137.5 ]
  ...
  [105.5  105.5  105.5 ]
  [162.5  162.5  162.5 ]
  [119.5  119.5  119.5 ]]

 [[121.   121.   121.  ]
  [216.75 216.75 216.75]
  [170.75 170.75 170.75]
  ...
  [156.   156.   156.  ]
  [116.   116.   116.  ]
  [ 76.5   76.5   76.5 ]]

 ...

 [[144.   144.   144.  ]
  [185.5  185.5  185.5 ]
  [128.75 128.75 128.75]
  ...
  [ 81.25  81.25  81.25]
  [112.   112.   112.  ]
  [134.   134.   134.  ]]

 [[ 81.25  81.25  81.25]
  [111.25 111.25 111.25]
  [102.25 102.25 102.25]
  ...
  [110.75 110.75 110.75]
  [167.75 167.75 167.75]
  [ 67.    67.    67.  ]]

 [[114.5  114.5  114.5 ]
  [ 53.5   53.5   53.5 ]
  [106.75 106.75 106.75]
  ...
  [124.75 124.75 124.75]
  [137.5  137.5  137.5 ]
  [128.5  128.5  128.5 ]]], shape=(128, 128, 3), dtype=float32