In [ ]:
#importing the libraries
import numpy as np
import gym

In [ ]:
#building the environment
env = gym.make('FrozenLake-v1', render_mode = 'human', new_step_api=True)

In [ ]:
#defining parameters
epsilon = 1.0
total_episodes = 5000
max_steps = 100
alpha = 0.1
gamma = 0.99
Q = np.zeros((env.observation_space.n, env.action_space.n))

In [ ]:
# Function to choose the next action using epsilon-greedy policy
def choose_action(state, Q, epsilon):
    if np.random.uniform(0, 1) < epsilon:
        return env.action_space.sample()
    else:
        return np.argmax(Q[state, :])

# Function to learn the Q value
def update(Q, state, state2, reward, action, action2, alpha, gamma):
    predict = Q[state, action]
    target = reward + gamma * Q[state2, action2]
    Q[state, action] = Q[state, action] + alpha * (target - predict)

In [ ]:
# SARSA learning
total_rewards = []
for episode in range(total_episodes):
    state1 = env.reset()
    action1 = choose_action(state1, Q, epsilon)
    t = 0
    episode_reward = 0

    while t < max_steps:
        env.render()
        result = env.step(action1)
        print(result)
        state2, reward, done, info = result[:4]
        #state2, reward, done, _ = env.step(action1)

        episode_reward += reward

        action2 = choose_action(state2, Q, epsilon)
        update(Q, state1, state2, reward, action1, action2, alpha, gamma)

        state1 = state2
        action1 = action2

        if done:
            break

        t += 1

    epsilon = max(0.1, epsilon * 0.995)  # Decay epsilon for exploration
    total_rewards.append(episode_reward)

    print(f"Episode {episode + 1} - Total Reward: {episode_reward}")

Streaming output truncated to the last 5000 lines.
(9, 0.0, False, False, {'prob': 0.3333333333333333})
(8, 0.0, False, False, {'prob': 0.3333333333333333})
(8, 0.0, False, False, {'prob': 0.3333333333333333})
(9, 0.0, False, False, {'prob': 0.3333333333333333})
(8, 0.0, False, False, {'prob': 0.3333333333333333})
(4, 0.0, False, False, {'prob': 0.3333333333333333})
(4, 0.0, False, False, {'prob': 0.3333333333333333})
(0, 0.0, False, False, {'prob': 0.3333333333333333})
(0, 0.0, False, False, {'prob': 0.3333333333333333})
(4, 0.0, False, False, {'prob': 0.3333333333333333})
(0, 0.0, False, False, {'prob': 0.3333333333333333})
(0, 0.0, False, False, {'prob': 0.3333333333333333})
(4, 0.0, False, False, {'prob': 0.3333333333333333})
(0, 0.0, False, False, {'prob': 0.3333333333333333})
(4, 0.0, False, False, {'prob': 0.3333333333333333})
(4, 0.0, False, False, {'prob': 0.3333333333333333})
(8, 0.0, False, False, {'prob': 0.3333333333333333})
(8, 0.0, False, False, {'prob': 0.33333333333333

KeyboardInterrupt: ignored

In [ ]:
# Evaluation
average_reward = sum(total_rewards) / total_episodes
print("Average performance:", average_reward)

# Visualizing the Q matrix
print(Q)


Average performance: 0.0398
[[2.44715722e-01 1.91667942e-01 1.92142047e-01 1.94234654e-01]
 [8.44933574e-02 9.67835978e-02 8.64122900e-02 1.92215630e-01]
 [1.87440067e-01 8.17385471e-02 9.10997131e-02 8.73788732e-02]
 [1.83076444e-05 1.51209469e-02 1.30239478e-03 0.00000000e+00]
 [2.69496525e-01 1.93442713e-01 1.18351682e-01 1.24103943e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.45703409e-01 6.95435077e-02 2.69437888e-01 3.28323716e-02]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.27174942e-01 2.29126741e-01 1.74041921e-01 3.08200674e-01]
 [2.81808690e-01 4.40140412e-01 3.05720347e-01 1.95751142e-01]
 [4.17898838e-01 3.04649034e-01 2.68140147e-01 1.74104576e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.73704043e-01 2.07550809e-01 5.58187115e-01 3.37561338e-01]
 [3.85511114e-01 5.08788373e-01 6.82707321e-01 4.16221531e-01]
 [0.00000000e+00 0.00000000

In [ ]:
#evaluation
print("performance:", reward/total_episodes)
#visualizing the Q matrix
print(Q)

performance: 0.0
[[2.44715722e-01 1.91667942e-01 1.92142047e-01 1.94234654e-01]
 [8.44933574e-02 9.67835978e-02 8.64122900e-02 1.92215630e-01]
 [1.87440067e-01 8.17385471e-02 9.10997131e-02 8.73788732e-02]
 [1.83076444e-05 1.51209469e-02 1.30239478e-03 0.00000000e+00]
 [2.69496525e-01 1.93442713e-01 1.18351682e-01 1.24103943e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.45703409e-01 6.95435077e-02 2.69437888e-01 3.28323716e-02]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.27174942e-01 2.29126741e-01 1.74041921e-01 3.08200674e-01]
 [2.81808690e-01 4.40140412e-01 3.05720347e-01 1.95751142e-01]
 [4.17898838e-01 3.04649034e-01 2.68140147e-01 1.74104576e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.73704043e-01 2.07550809e-01 5.58187115e-01 3.37561338e-01]
 [3.85511114e-01 5.08788373e-01 6.82707321e-01 4.16221531e-01]
 [0.00000000e+00 0.00000000e+00 0.0000

In [ ]:
# Defining parameters
epsilon = 1.0
total_episodes = 1000
max_steps = 100
alpha = 0.1
gamma = 0.99
Q = np.zeros((env.observation_space.n, env.action_space.n))

# Function to choose the next action using epsilon-greedy policy
def choose_action(state, Q, epsilon):
    if np.random.uniform(0, 1) < epsilon:
        return env.action_space.sample()
    else:
        return np.argmax(Q[state, :])

# Function to learn the Q value
def update(Q, state, state2, reward, action, action2, alpha, gamma):
    predict = Q[state, action]
    target = reward + gamma * Q[state2, action2]
    Q[state, action] = Q[state, action] + alpha * (target - predict)

# SARSA learning
total_rewards = []
for episode in range(total_episodes):
    state1 = env.reset()
    action1 = choose_action(state1, Q, epsilon)
    t = 0
    episode_reward = 0

    while t < max_steps:
        env.render()
        state2, reward, done, _ = env.step(action1)

        episode_reward += reward

        action2 = choose_action(state2, Q, epsilon)
        update(Q, state1, state2, reward, action1, action2, alpha, gamma)

        state1 = state2
        action1 = action2

        if done:
            break

        t += 1

    epsilon = max(0.1, epsilon * 0.995)  # Decay epsilon for exploration
    total_rewards.append(episode_reward)

    print(f"Episode {episode + 1} - Total Reward: {episode_reward}")

# Evaluation
average_reward = sum(total_rewards) / total_episodes
print("Average performance:", average_reward)

# Visualizing the Q matrix
print(Q)
